---
# tasks file for system-profile
- name: Adding test block
  lineinfile:
    path: /etc/profile
    line: '#This is a test block added by Ansible......adminuser'
    insertafter: EOF
    create: yes

- name: Set TMOUT environment variable in /etc/profile
  lineinfile:
    path: /etc/profile
    line: 'export TMOUT=1800'
    insertafter: EOF
